apiVersion: v1
kind: Service
metadata:
  name: nginx-static
  namespace: nginx-static
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30007